version: '3.7'
services:

  searcch-backend-local-dev:
    image: searcch-backend-local-dev
    container_name: searcch-backend-local-dev
    hostname: searcch-backend-local-dev
    restart: always
    build: .
    volumes:
      - ${DATADIR:-/data}/searcch-backend-local-dev/gunicorn_conf.py:/app/gunicorn_conf.py
      - ${DATADIR:-/data}/searcch-backend-local-dev/config-local-dev.py:/app/config-local-dev.py
      - ${DATADIR:-/data}/searcch-backend-local-dev/logs:/app/logs
    env_file:
      - env/searcch-backend-local-dev.env
    networks:
      - searcch-backend-local-dev-net
      - searcch-frontend-local-dev-net
    depends_on:
      - searcch-local-dev-postgres

  searcch-local-dev-postgres:
    image: postgres:14
    privileged: true
    container_name: searcch-local-dev-postgres
    hostname: searcch-local-dev-postgres
    restart: unless-stopped
    volumes:
      - ${DATADIR:-/data}/searcch-local-dev-psql:/var/lib/postgresql/data
    env_file:
      - env/local-dev-postgres.env
    networks:
      - searcch-backend-local-dev-net

networks:
  searcch-backend-local-dev-net:
    name: searcch-backend-local-dev-net
  searcch-frontend-local-dev-net:
    name: searcch-frontend-local-dev-net

