version: '3.7'
services:

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy/data:/data
      - /data/caddy/config:/config
      - /data/caddy/ssl/:/etc/ssl/certs/searcch/
    networks:
      - searcch-frontend-prod-net
      - searcch-frontend-dev-net

  searcch-backend-prod:
    image: searcch-backend-prod
    container_name: searcch-backend-prod
    restart: unless-stopped
    build: "https://${TOKEN:-token-here}:@github.com/ITI/searcch-backend.git"
    volumes:
      - /data/searcch-backend-prod/gunicorn_conf.py:/app/gunicorn_conf.py
      - /data/searcch-backend-prod/backend_config_production.py:/app/config-production.py
    env_file:
      - env/searcch-backend-prod.env
    networks:
      - searcch-backend-prod-net
      - searcch-frontend-prod-net
    depends_on:
      - searcch-prod-postgres

  searcch-backend-dev:
    image: searcch-backend-dev
    container_name: searcch-backend-dev
    hostname: searcch-backend-dev
    restart: unless-stopped
    #build: "https://${TOKEN:-token-here}:@github.com/ITI/searcch-backend.git#dev"
    build: .
    volumes:
      - /data/searcch-backend-dev/gunicorn_conf.py:/app/gunicorn_conf.py
      - /data/searcch-backend-dev/config-development.py:/app/config-development.py
      - /data/searcch-backend-dev/logs:/app/logs
    env_file:
      - env/searcch-backend-dev.env
    networks:
      - searcch-backend-dev-net
      - searcch-frontend-dev-net
    depends_on:
      - searcch-dev-postgres

  searcch-backend-local-dev:
    image: searcch-backend-local-dev
    container_name: searcch-backend-local-dev
    hostname: searcch-backend-local-dev
    build: .
    volumes:
      - /data/searcch-backend-local-dev/gunicorn_conf.py:/app/gunicorn_conf.py
      - /data/searcch-backend-local-dev/config-local-dev.py:/app/config-local-dev.py
      - /data/searcch-backend-local-dev/logs:/app/logs
    env_file:
      - env/searcch-backend-local-dev.env
    networks:
      - searcch-backend-local-dev-net
      - searcch-frontend-local-dev-net
    depends_on:
      - searcch-local-dev-postgres
    ports:
      - "80"

  searcch-prod-postgres:
    image: postgres
    container_name: searcch-prod-postgres
    hostname: searcch-prod-postgres
    restart: unless-stopped
    volumes:
      - /data/searcch-prod-psql:/var/lib/postgresql/data
    env_file:
      - env/prod-postgres.env
    networks:
      - searcch-backend-prod-net

  searcch-dev-postgres:
    image: postgres
    container_name: searcch-dev-postgres
    hostname: searcch-dev-postgres
    restart: unless-stopped
    volumes:
      - /data/searcch-dev-psql:/var/lib/postgresql/data
    env_file:
      - env/dev-postgres.env
    networks:
      - searcch-backend-dev-net

  searcch-local-dev-postgres:
    image: postgres
    container_name: searcch-local-dev-postgres
    hostname: searcch-local-dev-postgres
    restart: unless-stopped
    volumes:
      - /data/searcch-local-dev-psql:/var/lib/postgresql/data
    env_file:
      - env/local-dev-postgres.env
    networks:
      - searcch-backend-local-dev-net
    ports:
      - "5432"

networks:
  searcch-backend-dev-net:
    name: searcch-backend-dev-net
  searcch-backend-prod-net:
    name: searcch-backend-prod-net
  searcch-backend-local-dev-net:
    name: searcch-backend-local-dev-net
  searcch-frontend-dev-net:
    name: searcch-frontend-dev-net
  searcch-frontend-prod-net:
    name: searcch-frontend-prod-net
  searcch-frontend-local-dev-net:
    name: searcch-frontend-local-dev-net

