version: '3.7'
services:

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "4443:5443"
    volumes:
      - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy/data:/data
      - /data/caddy/config:/config
      - /data/caddy/ssl/:/etc/ssl/certs/searcch/
    networks:
      - searcch-frontend-prod-net
      - searcch-frontend-dev-net

  searcch-backend-prod:
    image: searcch-backend-prod
    container_name: searcch-backend-development
    build: "https://${TOKEN:-token-here}:@github.com/ITI/searcch-backend.git"
    volumes:
      - /data/searcch-backend-prod/gunicorn_conf.py:/app/gunicorn_conf.py
      - /data/searcch-backend-prod/backend_config_production.py:/app/config-production.py
    env_file:
      - env/backend-prod.env
    networks:
      - searcch-backend-prod-net
      - searcch-frontend-prod-net
    depends_on:
      - searcch-prod-postgres

  searcch-backend-dev:
    image: searcch-backend-dev
    container_name: searcch-backend-development
    build: "https://${TOKEN:token-here}:@github.com/ITI/searcch-backend.git#dev"
    volumes:
      - /data/searcch-backend-dev/gunicorn_conf.py:/app/gunicorn_conf.py
      - /data/searcch-backend-dev/config-development.py:/app/config-development.py
    env_file:
      - env/backend-dev.env
    networks:
      - searcch-backend-dev-net
      - searcch-frontend-dev-net
    depends_on:
      - searcch-dev-postgres

  searcch-prod-postgres:
    image: postgres
    container_name: searcch-prod-postgres
    volumes:
      - /data/searcch-prod-psql:/var/lib/postgresql/data
    env_file:
      - env/prod-postgres.env
    networks:
      - searcch-backend-prod-net

  searcch-dev-postgres:
    image: postgres
    container_name: searcch-dev-postgres
    volumes:
      - /data/searcch-dev-psql:/var/lib/postgresql/data
    env_file:
      - env/dev-postgres.env
    networks:
      - searcch-backend-dev-net

networks:
  searcch-backend-dev-net:
    name: searcch-backend-dev-net
  searcch-backend-prod-net:
    name: searcch-backend-prod-net
  searcch-frontend-dev-net:
    name: searcch-frontend-dev-net
  searcch-frontend-prod-net:
    name: searcch-frontend-prod-net
