"""‘aAdd_Column_Public_key_to_Persons_table

Revision ID: 091b654c3d9b
Revises: d8e9ac9996fe
Create Date: 2023-08-22 17:08:17.641584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '091b654c3d9b'
down_revision = 'd8e9ac9996fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('artifact_search_view',
    # sa.Column('dummy_id', sa.Integer(), nullable=False),
    # sa.Column('artifact_group_id', sa.Integer(), nullable=False),
    # sa.Column('artifact_id', sa.Integer(), nullable=True),
    # sa.Column('doc_vector', postgresql.TSVECTOR(), nullable=True),
    # sa.ForeignKeyConstraint(['artifact_group_id'], ['artifact_groups.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('dummy_id')
    # )
    # op.drop_table('alembic_lock')
    # op.drop_constraint('artifact_reviews_artifact_group_id_fkey', 'artifact_reviews', type_='foreignkey')
    op.add_column('persons', sa.Column('public_key', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'public_key')
    # op.create_foreign_key('artifact_reviews_artifact_group_id_fkey', 'artifact_reviews', 'artifact_groups', ['artifact_group_id'], ['id'])
    # op.create_table('alembic_lock',
    # sa.Column('locked', sa.BOOLEAN(), autoincrement=False, nullable=True)
    # )
    # op.drop_table('artifact_search_view')
    # ### end Alembic commands ###
