"""user-admin

Revision ID: 0ec7a7fb6f7b
Revises: 99cd8335be66
Create Date: 2021-07-31 04:08:46.667637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ec7a7fb6f7b'
down_revision = '99cd8335be66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('is_admin', sa.Boolean(), nullable=True, default=False))
    op.execute("update sessions set is_admin=False")
    op.alter_column(
        'sessions', 'is_admin',
        existing_type=sa.Boolean(),nullable=False)
    op.add_column('users', sa.Column('can_admin', sa.Boolean(), nullable=True, default=False))
    op.execute("update users set can_admin=False")
    op.alter_column(
        'users', 'can_admin',
        existing_type=sa.Boolean(),nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_admin')
    op.drop_column('sessions', 'is_admin')
    # ### end Alembic commands ###
