"""create artifact_owner_request table

Revision ID: 1648f292a8c6
Revises: 900a20bb0c3f
Create Date: 2022-08-11 18:01:57.772936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1648f292a8c6'
down_revision = '900a20bb0c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_owner_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artifact_group_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'pre_approved', name='artifact_owner_request_status_enum'), nullable=False),
    sa.Column('action_message', sa.Text(), nullable=True),
    sa.Column('action_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_group_id'], ['artifact_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_group_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifact_owner_request')
    # ### end Alembic commands ###
