"""remove subject column from artifact_reviews table

Revision ID: 1cc167c394bc
Revises: 5719ad4da4b4
Create Date: 2021-06-18 17:36:25.555024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cc167c394bc'
down_revision = '5719ad4da4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifact_reviews', 'subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifact_reviews', sa.Column('subject', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
