"""badges

Revision ID: 2aa29edc2096
Revises: 530e0b21aacd
Create Date: 2021-07-21 16:35:26.423034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column
import datetime

# revision identifiers, used by Alembic.
revision = '2aa29edc2096'
down_revision = '530e0b21aacd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=256), nullable=False),
    sa.Column('organization', sa.String(length=1024), nullable=False),
    sa.Column('venue', sa.String(length=1024), nullable=True),
    sa.Column('issue_time', sa.DateTime(), nullable=True),
    sa.Column('doi', sa.String(length=128), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'url', 'version', 'organization')
    )
    op.create_table('artifact_badges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'badge_id')
    )
    data_upgrades()
    # ### end Alembic commands ###

def data_upgrades():

    my_table = table('badges',
        column('title', sa.String),
        column('url', sa.String),
        column('image_url', sa.String),
        column('description_url', sa.String),
        column('description', sa.String),
        column('version', sa.String),
        column('organization', sa.String),
        column('issue_time', sa.DateTime),
        column('doi', sa.String),
        column('verified', sa.Boolean))

    op.bulk_insert(my_table,[
        dict(
            title="Artifacts Evaluated – Functional",
            url="https://www.acm.org/publications/policies/artifact-review-badging#functional",
            image_url="https://www.acm.org/binaries/content/gallery/acm/publications/replication-badges/artifacts_evaluated_functional_dl.jpg",
            description="The artifacts associated with the research are found to be documented, consistent, complete, exercisable, and include appropriate evidence of verification and validation.",
            version="1.0",
            organization="Association for Computing Machinery",
            issue_time=datetime.datetime(2020,8,24),
            doi=None,
            verified=True),
        dict(
            title="Artifacts Evaluated – Reusable",
            url="https://www.acm.org/publications/policies/artifact-review-badging#reusable",
            image_url="https://www.acm.org/binaries/content/gallery/acm/publications/replication-badges/artifacts_evaluated_reusable_dl.jpg",
            description="The artifacts associated with the paper are of a quality that significantly exceeds minimal functionality. That is, they have all the qualities of the Artifacts Evaluated – Functional level, but, in addition, they are very carefully documented and well-structured to the extent that reuse and repurposing is facilitated. In particular, norms and standards of the research community for artifacts of this type are strictly adhered to.",
            version="1.0",
            organization="Association for Computing Machinery",
            issue_time=datetime.datetime(2020,8,24),
            doi=None,
            verified=True),
        dict(
            title="Artifacts Available",
            url="https://www.acm.org/publications/policies/artifact-review-badging#available",
            image_url="https://www.acm.org/binaries/content/gallery/acm/publications/replication-badges/artifacts_available_dl.jpg",
            description="Author-created artifacts relevant to this paper have been placed on a publically accessible archival repository. A DOI or link to this repository along with a unique identifier for the object is provided.",
            version="1.0",
            organization="Association for Computing Machinery",
            issue_time=datetime.datetime(2020,8,24),
            doi=None,
            verified=True),
        dict(
            title="Results Reproduced",
            url="https://www.acm.org/publications/policies/artifact-review-badging#reproduced",
            image_url="https://www.acm.org/binaries/content/gallery/acm/publications/replication-badges/results_reproduced_dl.jpg",
            description="The main results of the paper have been independently obtained in a subsequent study by a person or team other than the authors, without the use of author-supplied artifacts.",
            version="1.0",
            organization="Association for Computing Machinery",
            issue_time=datetime.datetime(2020,8,24),
            doi=None,
            verified=True),
        dict(
            title="Results Replicated",
            url="https://www.acm.org/publications/policies/artifact-review-badging#replicated",
            image_url="https://www.acm.org/binaries/content/gallery/acm/publications/replication-badges/results_replicated_dl.jpg",
            description="The main results of the paper have been obtained in a subsequent study by a person or team other than the authors, using, in part, artifacts provided by the author.",
            version="1.0",
            organization="Association for Computing Machinery",
            issue_time=datetime.datetime(2020,8,24),
            doi=None,
            verified=True),

        dict(
            title="Artifacts Evaluated – Functional v1.1",
            url="https://www.acm.org/publications/policies/artifact-review-and-badging-current#functional",
            image_url="https://www.acm.org/binaries/content/gallery/acm/publications/replication-badges/artifacts_evaluated_functional_dl.jpg",
            description="The artifacts associated with the research are found to be documented, consistent, complete, exercisable, and include appropriate evidence of verification and validation.",
            version="1.0",
            organization="Association for Computing Machinery",
            issue_time=datetime.datetime(2020,8,24),
            doi=None,
            verified=True),
        dict(
            title="Artifacts Evaluated – Reusable v1.1",
            url="https://www.acm.org/publications/policies/artifact-review-and-badging-current#reusable",
            image_url="https://www.acm.org/binaries/content/gallery/acm/publications/replication-badges/artifacts_evaluated_reusable_dl.jpg",
            description="The artifacts associated with the paper are of a quality that significantly exceeds minimal functionality. That is, they have all the qualities of the Artifacts Evaluated – Functional level, but, in addition, they are very carefully documented and well-structured to the extent that reuse and repurposing is facilitated. In particular, norms and standards of the research community for artifacts of this type are strictly adhered to.",
            version="1.0",
            organization="Association for Computing Machinery",
            issue_time=datetime.datetime(2020,8,24),
            doi=None,
            verified=True),
        dict(
            title="Artifacts Available v1.1",
            url="https://www.acm.org/publications/policies/artifact-review-and-badging-current#available",
            image_url="https://www.acm.org/binaries/content/gallery/acm/publications/replication-badges/artifacts_available_dl.jpg",
            description="Author-created artifacts relevant to this paper have been placed on a publically accessible archival repository. A DOI or link to this repository along with a unique identifier for the object is provided.",
            version="1.0",
            organization="Association for Computing Machinery",
            issue_time=datetime.datetime(2020,8,24),
            doi=None,
            verified=True),
        dict(
            title="Results Reproduced v1.1",
            url="https://www.acm.org/publications/policies/artifact-review-and-badging-current#reproduced",
            image_url="https://www.acm.org/binaries/content/gallery/acm/publications/replication-badges/results_reproduced_dl.jpg",
            description="The main results of the paper have been obtained in a subsequent study by a person or team other than the authors, using, in part, artifacts provided by the author.",
            version="1.0",
            organization="Association for Computing Machinery",
            issue_time=datetime.datetime(2020,8,24),
            doi=None,
            verified=True),
        dict(
            title="Results Replicated",
            url="https://www.acm.org/publications/policies/artifact-review-and-badging-current#replicated",
            image_url="https://www.acm.org/binaries/content/gallery/acm/publications/replication-badges/results_replicated_dl.jpg",
            description="The main results of the paper have been independently obtained in a subsequent study by a person or team other than the authors, without the use of author-supplied artifacts.",
            version="1.0",
            organization="Association for Computing Machinery",
            issue_time=datetime.datetime(2020,8,24),
            doi=None,
            verified=True),

        dict(
            title="Open Data",
            url="https://osf.io/tvyxz/wiki/1.%20View%20the%20Badges/#opendata",
            image_url="https://imgur.com/Ecb5E8C",
            description="The Open Data badge is awarded when digitally-shareable data necessary to reproduce the reported results are publicly available.",
            version="",
            organization="Center For Open Science",
            issue_time=datetime.datetime(2019,5,6,18,52,16),
            doi=None,
            verified=True),
        dict(
            title="Open Materials",
            url="https://osf.io/tvyxz/wiki/1.%20View%20the%20Badges/#openmaterials",
            image_url="https://i.imgur.com/NkuGiDc.png",
            description="The Open Materials badge is earned by making publicly available the components of the research methodology needed to reproduce the reported procedure and analysis.",
            version="",
            organization="Center For Open Science",
            issue_time=datetime.datetime(2019,5,6,18,52,16),
            doi=None,
            verified=True),
        dict(
            title="Preregistered",
            url="https://osf.io/tvyxz/wiki/1.%20View%20the%20Badges/#preregistered",
            image_url="https://i.imgur.com/NkuGiDc.png",
            description="The Preregistered badge is earned for having a preregistered design. A preregistered design includes: (1) Description of the research design and study materials including planned sample size, (2) Description of motivating research question or hypothesis, (3) Description of the outcome variable(s), and (4) Description of the predictor variables including controls, covariates, independent variables (conditions). When possible, the study materials themselves are included in the preregistration.",
            version="",
            organization="Center For Open Science",
            issue_time=datetime.datetime(2019,5,6,18,52,16),
            doi=None,
            verified=True),
        dict(
            title="Preregistered+Analysis Plan",
            url="https://osf.io/tvyxz/wiki/1.%20View%20the%20Badges/#preregisteredplus",
            image_url="https://i.imgur.com/4aGad90.png",
            description="The Preregistered+Analysis Plan badge is earned for having a preregistered research design (described above) and an analysis plan for the research and reporting results according to that plan. An analysis plan includes specification of the variables and the analyses that will be conducted. Guidance on construction of an analysis plan is below.",
            version="",
            organization="Center For Open Science",
            issue_time=datetime.datetime(2019,5,6,18,52,16),
            doi=None,
            verified=True),

        dict(
            title="Code Available",
            url="https://ieeexplore.ieee.org/Xplorehelp/overview-of-ieee-xplore/about-content?code-available#reproducibility-badges",
            image_url="https://ieeexplore.ieee.org/Xplorehelp/img/badge_code_available.png",
            description="Available: Code is available as a supplement to the document.",
            version="",
            organization="IEEE",
            issue_time=datetime.datetime(2019,11,1),
            doi="10.1109/MC.2019.2935265",
            verified=True),
        dict(
            title="Datasets Available",
            url="https://ieeexplore.ieee.org/Xplorehelp/overview-of-ieee-xplore/about-content?datasets-available#reproducibility-badges",
            image_url="https://ieeexplore.ieee.org/Xplorehelp/img/badge_datasets_available.png",
            description="Available: Datasets are available as a supplement to the document.",
            version="",
            organization="IEEE",
            issue_time=datetime.datetime(2019,11,1),
            doi="10.1109/MC.2019.2935265",
            verified=True),
        dict(
            title="Code Reviewed",
            url="https://ieeexplore.ieee.org/Xplorehelp/overview-of-ieee-xplore/about-content?code-reviewed#reproducibility-badges",
            image_url="https://ieeexplore.ieee.org/Xplorehelp/img/badge_code_reviewed.png",
            description="Available: Code is available as a supplement to the document.",
            version="",
            organization="IEEE",
            issue_time=datetime.datetime(2019,11,1),
            doi="10.1109/MC.2019.2935265",
            verified=True),
        dict(
            title="Datasets Reviewed",
            url="https://ieeexplore.ieee.org/Xplorehelp/overview-of-ieee-xplore/about-content?datasets-reviewed#reproducibility-badges",
            image_url="https://ieeexplore.ieee.org/Xplorehelp/img/badge_datasets_reviewed.png",
            description="Available: Datasets are available as a supplement to the document.",
            version="",
            organization="IEEE",
            issue_time=datetime.datetime(2019,11,1),
            doi="10.1109/MC.2019.2935265",
            verified=True),

        dict(
            title="Artifacts Available",
            url="https://sysartifacts.github.io/osdi2020/usenixbadges-available.png",
            image_url="https://sysartifacts.github.io/osdi2020/usenixbadges-available.png",
            description="The artifacts associated with the paper have been made available for retrieval, permanently and publicly.",
            version="",
            organization="USENIX",
            issue_time=None,
            doi=None,
            verified=True),
        dict(
            title="Artifacts Functional",
            url="https://sysartifacts.github.io/osdi2020/usenixbadges-functional.png",
            image_url="https://sysartifacts.github.io/osdi2020/usenixbadges-functional.png",
            description="The artifacts conform to the expectations set by the paper in terms of functionality, usability, and relevance.",
            version="",
            organization="USENIX",
            issue_time=None,
            doi=None,
            verified=True),
        dict(
            title="Results Reproduced",
            url="https://sysartifacts.github.io/osdi2020/usenixbadges-reproduced.png",
            image_url="https://sysartifacts.github.io/osdi2020/usenixbadges-reproduced.png",
            description="The artifacts can be used to obtain the main results presented in the paper.",
            version="",
            organization="USENIX",
            issue_time=None,
            doi=None,
            verified=True),
        dict(
            title="Artifact Evaluated - Passed",
            url="https://www.usenix.org/sites/default/files/artifact_evaluation_badge_250.png",
            image_url="https://www.usenix.org/sites/default/files/artifact_evaluation_badge_250.png",
            description="Artifact Evaluated - Passed",
            version="",
            organization="USENIX",
            issue_time=None,
            doi=None,
            verified=True),
        dict(
            title="Artifact Evaluated",
            url="https://www.usenix.org/sites/default/files/usenix_artifact_evaluated_250.png",
            image_url="https://www.usenix.org/sites/default/files/usenix_artifact_evaluated_250.png",
            description="Artifact Evaluated",
            version="",
            organization="USENIX",
            issue_time=None,
            doi=None,
            verified=True)
    ]
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifact_badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
