"""ownership invitations

Revision ID: 3f0587369488
Revises: f29a393d7f66
Create Date: 2023-03-08 21:35:59.457631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f0587369488'
down_revision = 'f29a393d7f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ownership_invitation_keys',
    sa.Column('email', sa.String(256), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('ownership_invitations',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('artifact_group_id', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_group_id'], ['artifact_groups.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'artifact_group_id')
    )
    op.add_column('persons', sa.Column('opt_out', sa.Boolean(), nullable=False, server_default='False'))
    op.alter_column('persons', 'opt_out', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'opt_out')
    op.drop_table('ownership_invitations')
    op.drop_table('ownership_invitation_keys')
    # ### end Alembic commands ###
