"""add column action_by_user_id to artifact_owner_request

Revision ID: 43d79542de81
Revises: 1648f292a8c6
Create Date: 2022-08-18 01:38:06.254482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43d79542de81'
down_revision = '1648f292a8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifact_owner_request', sa.Column('action_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artifact_owner_request', 'users', ['action_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artifact_owner_request', type_='foreignkey')
    op.drop_column('artifact_owner_request', 'action_by_user_id')
    # ### end Alembic commands ###
