"""org_url

Revision ID: 6458fd36a501
Revises: 5d62591b020f
Create Date: 2021-07-22 23:53:40.583579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6458fd36a501'
down_revision = '5d62591b020f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'url')
    # ### end Alembic commands ###
