"""refactor-org

Revision ID: 67619401b55d
Revises: 79f3942539dc
Create Date: 2021-07-15 16:44:43.836528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67619401b55d'
down_revision = '79f3942539dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('verified', sa.Boolean(), nullable=True, default=False))
    op.execute("update organizations set verified=False where verified is NULL")
    op.execute("update organizations set verified=True where address is not NULL")
    op.alter_column(
        'organizations', 'verified',
        existing_type=sa.Boolean(),nullable=False)
    op.drop_constraint('organizations_name_type_parent_org_id_key', 'organizations', type_='unique')
    op.drop_constraint('organizations_parent_org_id_fkey', 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'parent_org_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('parent_org_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('organizations_parent_org_id_fkey', 'organizations', 'organizations', ['parent_org_id'], ['id'])
    op.create_unique_constraint('organizations_name_type_parent_org_id_key', 'organizations', ['name', 'type', 'parent_org_id'])
    op.drop_column('organizations', 'verified')
    # ### end Alembic commands ###
