"""create stat collection tables

Revision ID: 900a20bb0c3f
Revises: 6b9d62c4df34
Create Date: 2022-05-24 21:02:09.899716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '900a20bb0c3f'
down_revision = '6b9d62c4df34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats_searches',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('search_term', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recent_views',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('artifact_group_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['artifact_group_id'], ['artifact_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('stats_views',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('artifact_group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['artifact_group_id'], ['artifact_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats_searches')
    op.drop_table('recent_views')
    op.drop_table('stats_views')
    # ### end Alembic commands ###
