"""claim-artifact table

Revision ID: ab36433d94b9
Revises: 3b98c44ef5b2
Create Date: 2022-03-18 21:52:39.824341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab36433d94b9'
down_revision = '3b98c44ef5b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_artifact_ownership',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approving_user_id', sa.Integer(), nullable=True),
    sa.Column('approval_message', sa.Text(), nullable=True),
    sa.Column('approval_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approving_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_artifact_ownership')
    # ### end Alembic commands ###