"""user-sso-token-constraint

Revision ID: affe7228e4ef
Revises: 0ec7a7fb6f7b
Create Date: 2021-08-09 15:00:37.828025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'affe7228e4ef'
down_revision = '0ec7a7fb6f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sessions_user_id_sso_token_key', 'sessions', type_='unique')
    op.create_unique_constraint('sessions_sso_token_key', 'sessions', ['sso_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sessions_sso_token_key', 'sessions', type_='unique')
    op.create_unique_constraint('sessions_user_id_sso_token_key', 'sessions', ['user_id', 'sso_token'])
    # ### end Alembic commands ###
