"""add_artifact_id_pk_labels

Revision ID: d8dc7021a65f
Revises: 091b654c3d9b
Create Date: 2023-09-15 05:14:54.908516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8dc7021a65f'
down_revision = '091b654c3d9b'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_constraint("labels_pkey", "labels", type_="unique")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("labels_pkey", "labels", type_="primary")
    # ### end Alembic commands ###
