TESTING = True
DEBUG = True
SQLALCHEMY_ECHO = True
SQLALCHEMY_TRACK_MODIFICATIONS = True
#SESSION_TIMEOUT_IN_MINUTES = 60
SESSION_TIMEOUT_IN_MINUTES = 24*60
SQLALCHEMY_DATABASE_URI = "postgresql+psycopg2cffi://postgres:postgres@searcch-local-dev-postgres:5432/searcchhub_devel"
SHARED_SECRET_KEY = "shared_secret_key"
DB_AUTO_MIGRATE = True
FRONTEND_URL="http://localhost:3000"
ADMIN_MAILING_RECIPIENTS = ['searcch-hub@cyberexperimentation.org']
MAIL_DEFAULT_SENDER = 'searcch-hub@cyberexperimentation.org'
MAIL_SERVER = "searcch-backend-postfix"
EMAIL_INTERVAL_DAYS = 30